import assert from 'node:assert/strict';import test from 'node:test';import{createRequire}from'node:module';import{readFileSync}from'node:fs';import{resolve}from'node:path';import{runInNewContext}from'node:vm';import ts from'typescript';
const real=createRequire(import.meta.url),id='11300000-0000-4000-8000-000000000010';
const week=()=>({lun:{on:true,franjas:[['09:00','12:00']]},mar:{on:false,franjas:[]},mie:{on:false,franjas:[]},jue:{on:false,franjas:[]},vie:{on:false,franjas:[]},sab:{on:false,franjas:[]},dom:{on:false,franjas:[]}});
function load(failRead=false, snapshot:unknown={revision:2,protectedDates:false,franjas:[{dia_semana:1,hora_inicio:"09:00",hora_fin:"12:00"}]}){const calls:Array<{name:string;args:Record<string,unknown>}>=[];const client={rpc:async(name:string,args:Record<string,unknown>)=>{calls.push({name,args});return failRead?{data:null,error:{code:'08006',message:'synthetic failure'}}:{data:name==="read_availability_snapshot"?snapshot:{revision:2,count:1},error:null}},from:(name:string)=>{const result={data:name==='servicio'?[]:name==='organization'?{}:null,error:name==='disponibilidad_profesional'?{code:'08006',message:'synthetic failure'}:null};const q={select:()=>q,eq:()=>q,order:()=>q,maybeSingle:async()=>result,then:(resolve:(r:unknown)=>unknown)=>Promise.resolve(result).then(resolve)};return q}};
 const mocks:Record<string,unknown>={'@/lib/crypto':{},'@/lib/supabase/server':{createSupabaseServerClient:async()=>client},'./active-context':{getActiveContext:async()=>({ok:true,data:{organization:{id,nombre:'Synthetic',slug:'synthetic',tipo:'INDEPENDIENTE'},profile:{nombre:'Synthetic',apellido:'',email:'synthetic@example.invalid'},session:{organizationId:id,memberId:id,role:'OWNER'}}})}};const exports:Record<string,(x?:unknown)=>Promise<unknown>>={};runInNewContext(ts.transpileModule(readFileSync('lib/db/configuracion.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,Date,JSON,structuredClone,require:(name:string)=>name in mocks?mocks[name]:real(name.startsWith('@/')?resolve(name.slice(2)):name.startsWith('./')?resolve('lib/db',name):name)});return{exports,calls};}
test('inverted or overlapping enabled hours fail before any replacement',async()=>{for(const franjas of [[['12:00','09:00']],[['09:00','12:00'],['11:00','13:00']]]){const a=load(),dias=week();dias.lun.franjas=franjas;const result=await a.exports.saveHorarios({dias,organizationId:id,memberId:id,revision:1,operacionId:id}) as {ok:boolean};assert.equal(result.ok,false);assert.equal(a.calls.length,0)}});
test('failed availability read cannot become an empty editable schedule',async()=>{const a=load(true);const result=await a.exports.getConfiguracionData() as {ok:boolean};assert.equal(result.ok,false)});
test('save sends expected context, revision and stable operation to the atomic writer',async()=>{const a=load();const result=await a.exports.saveHorarios({dias:week(),organizationId:id,memberId:id,revision:1,operacionId:id}) as {ok:boolean;data:{revision:number}};assert.equal(result.ok,true);assert.equal(a.calls[0].name,'save_availability_revision');assert.equal(a.calls[0].args.p_expected_revision,1);assert.equal(a.calls[0].args.p_operation,id);assert.equal(result.data.revision,2)});

test('successful snapshot maps revision and complete week, malformed snapshot fails closed',async()=>{
 const a=load();const result=await a.exports.readHorarios({organizationId:id,memberId:id}) as {ok:boolean;data:{context:{revision:number};dias:ReturnType<typeof week>}};assert.equal(result.ok,true);assert.equal(result.data.context.revision,2);assert.equal(Object.keys(result.data.dias).length,7);assert.equal(result.data.dias.lun.franjas[0][0],'09:00');
 const b=load(false,{revision:1,protectedDates:false,franjas:[{dia_semana:9,hora_inicio:'09:00',hora_fin:'12:00'}]});assert.equal((await b.exports.readHorarios({organizationId:id,memberId:id}) as {ok:boolean}).ok,false);
});
test('stale organization/member context never reaches a database writer or reader',async()=>{
 for(const method of ['saveHorarios','readHorarios','getConfiguracionData']){const a=load();const result=await a.exports[method]({dias:week(),organizationId:'11300000-0000-4000-8000-000000000099',memberId:id,revision:1,operacionId:id}) as {ok:boolean};assert.equal(result.ok,false);assert.equal(a.calls.length,0);}
});
test('a complete explicit closed week is valid but missing or enabled-empty days fail',async()=>{
 const dias=week();dias.lun={on:false,franjas:[['','']]};const a=load();assert.equal((await a.exports.saveHorarios({dias,organizationId:id,memberId:id,revision:1,operacionId:id}) as {ok:boolean}).ok,true);assert.equal((a.calls[0].args.p_franjas as unknown[]).length,0);
 for(const dias of [{lun:{on:false,franjas:[]}}, {...week(),lun:{on:true,franjas:[]}}]){const b=load();assert.equal((await b.exports.saveHorarios({dias,organizationId:id,memberId:id,revision:1,operacionId:id}) as {ok:boolean}).ok,false);assert.equal(b.calls.length,0);}
});
test('same command retry and equivalent ordering preserve the request fingerprint',async()=>{
 const a=load(),dias=week(),input={dias,organizationId:id,memberId:id,revision:1,operacionId:id};await a.exports.saveHorarios(input);await a.exports.saveHorarios({...input,dias:Object.fromEntries(Object.entries(dias).reverse())});assert.equal(a.calls[0].args.p_hash,a.calls[1].args.p_hash);assert.equal(String(a.calls[0].args.p_hash).length,64);
});
