import assert from 'node:assert/strict';import test from 'node:test';import{readFileSync}from'node:fs';import{createRequire}from'node:module';import{resolve,dirname}from'node:path';import{runInNewContext}from'node:vm';import ts from'typescript';
const real=createRequire(import.meta.url);
function load(file:string,mocks:Record<string,unknown>){const exports:Record<string,(...args:unknown[])=>Promise<unknown>>={};runInNewContext(ts.transpileModule(readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,AbortSignal,Response,Date,JSON,require:(name:string)=>name in mocks?mocks[name]:name==='server-only'?{}:real(name.startsWith('@/')?resolve(name.slice(2)):name.startsWith('.')?resolve(dirname(file),name):name)});return exports;}
function scenario(options:{signedIn?:boolean;aal?:string;sessionValid?:boolean;factor?:boolean;denied?:boolean;sourceError?:boolean}={}){const calls:string[]=[];let hasSignal=false;const client={auth:{getUser:async()=>({data:{user:options.signedIn===false?null:{id:'synthetic',app_metadata:{role:'OWNER',operator:true}}},error:null}),mfa:{getAuthenticatorAssuranceLevel:async()=>({data:{currentLevel:options.aal??'aal2'},error:null})}},rpc:(name:string)=>{calls.push(name);if(name==='mfa_access_status')return Promise.resolve({data:{required:false,allowed:true,isStaff:true,hasVerifiedFactor:options.factor!==false,sessionValid:options.sessionValid!==false},error:null});return{abortSignal:(signal:AbortSignal)=>{hasSignal=signal instanceof AbortSignal;return Promise.resolve(options.denied?{data:null,error:{code:'42501',message:'raw sensitive SQL'}}:options.sourceError?{data:null,error:{code:'08006',message:'patient@invalid private SQL'}}:{data:{backup:{state:'no_report'}},error:null})}}}};const exports=load('lib/db/operations.ts',{'@/lib/supabase/server':{createSupabaseServerClient:async()=>client,createSupabaseServiceClient:()=>{throw Error('Privileged read forbidden')}}});return{exports,calls,hasSignal:()=>hasSignal};}
for(const options of [{signedIn:false},{aal:'aal1'},{sessionValid:false},{factor:false}])test(`operation server blocks insufficient session ${JSON.stringify(options)}`,async()=>{const s=scenario(options);assert.equal((await s.exports.getOperationsSnapshot() as {ok:boolean}).ok,false);assert.equal(s.calls.includes('operations_snapshot'),false)});
test('an OWNER claim does not bypass current database operator authorization',async()=>{const s=scenario({denied:true});const result=await s.exports.getOperationsSnapshot() as {ok:boolean;error:{code:string}};assert.equal(result.ok,false);assert.equal(result.error.code,'forbidden');assert.equal(JSON.stringify(result).includes('raw sensitive'),false);assert.equal(s.hasSignal(),true)});
test('source transport errors return unavailable without leaking SQL or fabricating zero usage',async()=>{const s=scenario({sourceError:true});const result=await s.exports.getOperationsSnapshot() as {ok:boolean};assert.equal(result.ok,false);assert.equal(JSON.stringify(result).includes('patient@invalid'),false)});
test('verified independent operator receives only normalized aggregate data',async()=>{const s=scenario();const result=await s.exports.getOperationsSnapshot() as {ok:boolean;data:{backup:{state:string};metrics:Array<{state:string}>}};assert.equal(result.ok,true);assert.equal(result.data.backup.state,'no_report');assert.ok(result.data.metrics.every(m=>m.state==='unknown'))});
for(const [code,status]of [['auth_required',401],['mfa_required',403],['forbidden',403],['db_error',503]]as const)test(`operations GET is private and fails closed ${code}`,async()=>{const api=load('app/api/operacion/route.ts',{'@/lib/db/operations':{getOperationsSnapshot:async()=>({ok:false,error:{code,message:'No disponible'}})}});const response=await api.GET() as Response;assert.equal(response.status,status);assert.match(response.headers.get('cache-control')??'',/private, no-store/);assert.equal(response.headers.get('vary'),'Cookie');assert.equal((await response.json()).ok,false)});

test('successful operations GET is also private and contains only the normalized snapshot',async()=>{
 const snapshot={generatedAt:null,queues:[],metrics:[],backup:{state:'no_report'}};
 const api=load('app/api/operacion/route.ts',{'@/lib/db/operations':{getOperationsSnapshot:async()=>({ok:true,data:snapshot})}});
 const response=await api.GET() as Response;
 assert.equal(response.status,200);
 assert.match(response.headers.get('cache-control')??'',/private, no-store/);
 assert.equal(response.headers.get('vary'),'Cookie');
 assert.deepEqual(await response.json(),{ok:true,data:snapshot});
});

